/**
 * Company logo resolver — maps stock tickers to their company website domains
 * for fetching logos via the Clearbit Logo API (free, no key required).
 *
 * Usage: getLogoUrl("AAPL") → "https://logo.clearbit.com/apple.com?size=80"
 *
 * Falls back to null for tickers without a known domain.
 */

const TICKER_TO_DOMAIN: Record<string, string> = {
  // ── Mega Cap Tech ──
  AAPL: "apple.com",
  MSFT: "microsoft.com",
  GOOGL: "google.com",
  GOOG: "google.com",
  AMZN: "amazon.com",
  META: "meta.com",
  NVDA: "nvidia.com",
  TSLA: "tesla.com",
  AVGO: "broadcom.com",
  ORCL: "oracle.com",
  ADBE: "adobe.com",
  CRM: "salesforce.com",
  CSCO: "cisco.com",
  INTC: "intel.com",
  IBM: "ibm.com",
  AMD: "amd.com",
  QCOM: "qualcomm.com",
  TXN: "ti.com",
  MU: "micron.com",
  AMAT: "appliedmaterials.com",
  LRCX: "lamresearch.com",
  KLAC: "kla.com",
  MRVL: "marvell.com",
  NXPI: "nxp.com",
  ADI: "analog.com",
  SNPS: "synopsys.com",
  CDNS: "cadence.com",
  MCHP: "microchip.com",
  ON: "onsemi.com",
  SWKS: "skyworksinc.com",
  MPWR: "monolithicpower.com",

  // ── Software & Internet ──
  NFLX: "netflix.com",
  SHOP: "shopify.com",
  NOW: "servicenow.com",
  SNOW: "snowflake.com",
  UBER: "uber.com",
  ABNB: "airbnb.com",
  SQ: "squareup.com",
  SPOT: "spotify.com",
  PINS: "pinterest.com",
  SNAP: "snap.com",
  COIN: "coinbase.com",
  PLTR: "palantir.com",
  NET: "cloudflare.com",
  DDOG: "datadoghq.com",
  ZS: "zscaler.com",
  CRWD: "crowdstrike.com",
  PANW: "paloaltonetworks.com",
  FTNT: "fortinet.com",
  TEAM: "atlassian.com",
  WDAY: "workday.com",
  VEEV: "veeva.com",
  TTD: "thetradedesk.com",
  ROKU: "roku.com",
  U: "unity.com",
  RBLX: "roblox.com",
  DOCU: "docusign.com",
  ZM: "zoom.us",
  OKTA: "okta.com",
  MDB: "mongodb.com",
  TWLO: "twilio.com",
  PAYC: "paycom.com",
  HUBS: "hubspot.com",

  // ── Finance ──
  JPM: "jpmorganchase.com",
  BAC: "bankofamerica.com",
  WFC: "wellsfargo.com",
  GS: "goldmansachs.com",
  MS: "morganstanley.com",
  C: "citigroup.com",
  BLK: "blackrock.com",
  SCHW: "schwab.com",
  AXP: "americanexpress.com",
  V: "visa.com",
  MA: "mastercard.com",
  PYPL: "paypal.com",
  COF: "capitalone.com",
  USB: "usbank.com",
  PNC: "pnc.com",
  TFC: "truist.com",
  BK: "bnymellon.com",
  CME: "cmegroup.com",
  ICE: "ice.com",
  SPGI: "spglobal.com",
  MCO: "moodys.com",
  MSCI: "msci.com",
  FIS: "fisglobal.com",
  AIG: "aig.com",
  MET: "metlife.com",
  PRU: "prudential.com",
  ALL: "allstate.com",
  TRV: "travelers.com",
  AFL: "aflac.com",
  CB: "chubb.com",

  // ── Healthcare & Pharma ──
  JNJ: "jnj.com",
  UNH: "unitedhealthgroup.com",
  PFE: "pfizer.com",
  ABBV: "abbvie.com",
  MRK: "merck.com",
  LLY: "lilly.com",
  TMO: "thermofisher.com",
  ABT: "abbott.com",
  DHR: "danaher.com",
  BMY: "bms.com",
  AMGN: "amgen.com",
  GILD: "gilead.com",
  ISRG: "intuitive.com",
  REGN: "regeneron.com",
  VRTX: "vrtx.com",
  MDT: "medtronic.com",
  SYK: "stryker.com",
  BSX: "bostonscientific.com",
  ZTS: "zoetis.com",
  CI: "cigna.com",
  ELV: "elevancehealth.com",
  HCA: "hcahealthcare.com",
  HUM: "humana.com",
  CVS: "cvshealth.com",
  MRNA: "modernatx.com",
  BIIB: "biogen.com",
  DXCM: "dexcom.com",

  // ── Consumer ──
  WMT: "walmart.com",
  HD: "homedepot.com",
  COST: "costco.com",
  PG: "pg.com",
  KO: "coca-colacompany.com",
  PEP: "pepsico.com",
  MCD: "mcdonalds.com",
  SBUX: "starbucks.com",
  NKE: "nike.com",
  TGT: "target.com",
  LOW: "lowes.com",
  TJX: "tjx.com",
  ROST: "rossstores.com",
  DG: "dollargeneral.com",
  DLTR: "dollartree.com",
  YUM: "yum.com",
  CMG: "chipotle.com",
  DPZ: "dominos.com",
  MNST: "monsterbevcorp.com",
  KHC: "kraftheinzcompany.com",
  GIS: "generalmills.com",
  K: "kellanova.com",
  SJM: "jmsmucker.com",
  CAG: "conagra.com",
  HSY: "thehersheycompany.com",
  CL: "colgatepalmolive.com",
  EL: "esteelauder.com",
  PM: "pmi.com",
  MO: "altria.com",

  // ── Industrial & Defense ──
  CAT: "cat.com",
  DE: "deere.com",
  BA: "boeing.com",
  RTX: "rtx.com",
  LMT: "lockheedmartin.com",
  NOC: "northropgrumman.com",
  GD: "gd.com",
  GE: "ge.com",
  HON: "honeywell.com",
  MMM: "3m.com",
  UPS: "ups.com",
  FDX: "fedex.com",
  UNP: "up.com",
  CSX: "csx.com",
  NSC: "norfolksouthern.com",
  WM: "wm.com",
  RSG: "republicservices.com",
  EMR: "emerson.com",
  ETN: "eaton.com",
  ITW: "itw.com",
  PH: "parker.com",
  ROK: "rockwellautomation.com",
  IR: "irco.com",

  // ── Energy ──
  XOM: "exxonmobil.com",
  CVX: "chevron.com",
  COP: "conocophillips.com",
  SLB: "slb.com",
  EOG: "eogresources.com",
  MPC: "marathonpetroleum.com",
  PSX: "phillips66.com",
  VLO: "valero.com",
  OXY: "oxy.com",
  PXD: "pxd.com",
  DVN: "devonenergy.com",
  HAL: "halliburton.com",
  FANG: "diamondbackenergy.com",
  BKR: "bakerhughes.com",
  KMI: "kindermorgan.com",
  WMB: "williams.com",
  OKE: "oneok.com",
  TRGP: "targa.com",

  // ── Telecom & Media ──
  DIS: "thewaltdisneycompany.com",
  CMCSA: "comcastcorporation.com",
  T: "att.com",
  VZ: "verizon.com",
  TMUS: "t-mobile.com",
  PARA: "paramount.com",
  WBD: "wbd.com",
  NWSA: "newscorp.com",
  EA: "ea.com",
  TTWO: "take2games.com",
  ATVI: "activision.com",

  // ── Real Estate ──
  AMT: "americantower.com",
  PLD: "prologis.com",
  CCI: "crowncastle.com",
  EQIX: "equinix.com",
  SPG: "simon.com",
  O: "realtyincome.com",
  PSA: "publicstorage.com",
  WELL: "welltower.com",
  DLR: "digitalrealty.com",
  AVB: "avalonbay.com",
  EQR: "equityresidential.com",

  // ── Materials ──
  LIN: "linde.com",
  APD: "airproducts.com",
  SHW: "sherwin-williams.com",
  ECL: "ecolab.com",
  FCX: "fcx.com",
  NEM: "newmont.com",
  NUE: "nucor.com",
  STLD: "steeldynamics.com",
  VMC: "vulcanmaterials.com",
  MLM: "martinmarietta.com",
  DOW: "dow.com",
  DD: "dupont.com",
  PPG: "ppg.com",
  ALB: "albemarle.com",

  // ── Utilities ──
  NEE: "nexteraenergy.com",
  DUK: "duke-energy.com",
  SO: "southerncompany.com",
  D: "dominionenergy.com",
  AEP: "aep.com",
  SRE: "sempra.com",
  EXC: "exeloncorp.com",
  XEL: "xcelenergy.com",
  WEC: "wecenergygroup.com",
  ED: "coned.com",
  ES: "eversource.com",
  AES: "aes.com",

  // ── Auto & Transport ──
  F: "ford.com",
  GM: "gm.com",
  RIVN: "rivian.com",
  LCID: "lucidmotors.com",
  DAL: "delta.com",
  UAL: "united.com",
  LUV: "southwest.com",
  AAL: "aa.com",

  // ── Other Notable ──
  BRK_B: "berkshirehathaway.com",
  "BRK.B": "berkshirehathaway.com",
  MGM: "mgmresorts.com",
  WYNN: "wynnresorts.com",
  LVS: "sands.com",
  MAR: "marriott.com",
  HLT: "hilton.com",
  BKNG: "booking.com",
  EXPE: "expedia.com",
  ARM: "arm.com",
  SMCI: "supermicro.com",
  DELL: "dell.com",
  HPQ: "hp.com",
  HPE: "hpe.com",
};

/**
 * Get the logo URL for a stock ticker.
 * Returns the Clearbit Logo API URL or null if the domain is unknown.
 */
export function getLogoUrl(ticker: string, size = 80): string | null {
  const domain = TICKER_TO_DOMAIN[ticker] || TICKER_TO_DOMAIN[ticker.replace(".", "_")];
  if (!domain) return null;
  return `https://logo.clearbit.com/${domain}?size=${size}`;
}

/**
 * Check if a ticker has a known logo domain.
 */
export function hasLogo(ticker: string): boolean {
  return ticker in TICKER_TO_DOMAIN || ticker.replace(".", "_") in TICKER_TO_DOMAIN;
}
